#!/usr/bin/env python3
"""Turn `nm -n` output into a C symbol table for kernel backtraces (roadmap K3).

    nm -n surfos.stage1 | tools/gensyms.py > ksyms.c

Only text symbols are kept. The table goes into the .ksyms section, which linker.ld
places after .text/.rodata/.data, so adding it does not move any code address: the
kernel is linked twice, once to learn the addresses and once with the table.
With no input (an empty stage-one table) it emits an empty table.
"""
import sys

syms = []
for line in sys.stdin:
    parts = line.split()
    if len(parts) != 3:
        continue
    addr, kind, name = parts
    if kind not in ('T', 't', 'W', 'w'):
        continue
    if name.startswith(('.L', '__ksym')) or name.startswith('isr') and name[3:].isdigit():
        continue  # local labels and the 256 trap stubs: noise in a backtrace
    syms.append((int(addr, 16), name))

syms.sort()
names = []
offsets = []
pos = 0
for addr, name in syms:
    offsets.append(pos)
    names.append(name)
    pos += len(name) + 1

print('/* generated by tools/gensyms.py: do not edit */')
print('#include <surfos/ksym.h>')
print('')
print('const u_long ksym_count __attribute__((section(".ksyms"))) = %d;' % len(syms))
print('')
print('const struct ksym ksym_table[%d] __attribute__((section(".ksyms"))) = {' % max(len(syms), 1))
if syms:
    for (addr, name), off in zip(syms, offsets):
        print('    { 0x%08x, %d },' % (addr, off))
else:
    print('    { 0, 0 },')
print('};')
print('')
print('const char ksym_names[] __attribute__((section(".ksyms"))) =')
if names:
    for name in names:
        print('    "%s\\0"' % name)
else:
    print('    ""')
print(';')
